### PR TITLE
Few small fixes to make it compilable on FreeBSD

### PR DESCRIPTION
**Pull request by glebius**

### CODE REVIEW

**Comment by ilya-fedin** [comment]
I don't really like that. Doesn't FreeBSD have pkgconfig file for jemalloc?

**Comment by glebius** [comment]
No, jemalloc is basically the system libc malloc in FreeBSD, part of the operating system distribution. pkgconfig is a third party tool, that is not a part of the OS.

**Comment by ilya-fedin** [comment]
Is it possible that freebsd also has jemalloc as a standalone package with pkgconfig file and generic header name somewhere in 'ports' or elsewhere?

**Comment by glebius** [comment]
Nope, there is no such port/package. It is not optional. Basically jemalloc was initially written as a libc malloc for FreeBSD, it is integral part of the system. See http://jemalloc.net.

**Comment by ilya-fedin** [comment]
I know, I know. I thought that maybe it's in libc and has advanced version as a package, built from the repository on github.

**Comment by ilya-fedin** [comment]
That looks better to me
```diff
diff --git a/external/jemalloc/CMakeLists.txt b/external/jemalloc/CMakeLists.txt
index c720bd6..0c0f0be 100644
--- a/external/jemalloc/CMakeLists.txt
+++ b/external/jemalloc/CMakeLists.txt
@@ -7,6 +7,10 @@
 add_library(external_jemalloc INTERFACE IMPORTED GLOBAL)
 add_library(desktop-app::external_jemalloc ALIAS external_jemalloc)
 
+if (CMAKE_SYSTEM_NAME STREQUAL "FreeBSD")
+    return()
+endif()
+
 if (DESKTOP_APP_USE_PACKAGED)
     find_package(PkgConfig REQUIRED)
     pkg_check_modules(JEMALLOC IMPORTED_TARGET jemalloc)
```

**Comment by glebius** [comment]
Well, it is up to you. I can't insist, since this is your software. But, IMHO, this looks more like a hack than what I suggest.

What my version does is that it creates a global cmake keyword, that cmake definitely lacks. This keyword might be useful in future, not only for the jemalloc thing. Then I'm using this keyword to disable a specific submodule.

What your version does is that we still enter the submodule that is not needed to be entered at all. This also strongly violates the surrounding style of the external/CMakeLists.txt. It routinely uses `if (LINUX)` to enable/disable certain submodules. Why would this one being disabled in such a different manner?

I don't think this also is going to work as is, since we still `add_library()` and we still have `target_link_libraries(desktop-app::external_jemalloc)` in options_linux.cmake.

**Comment by ilya-fedin** [comment]
> What my version does is that it creates a global cmake keyword, that cmake definitely lacks. This keyword might be useful in future, not only for the jemalloc thing. Then I'm using this keyword to disable a specific submodule.

I don't think creating keyword for only one of BSDs and for one-time use only is a good idea.

> Why would this one being disabled in such a different manner?

The check for LINUX (what is actually `NOT WIN32 AND NOT APPLE`) doesn't need additional conditions in options_linux.cmake and other unix-related files, while the check for FreeBSD does So it should exist as an implementation detail, like e.g. the check for DESKTOP_APP_USE_PACKAGED_LAZY in external/hime_qt/CMakeLists.txt

> I don't think this also is going to work as is, since we still `add_library()` and we still have `target_link_libraries(desktop-app::external_jemalloc)` in options_linux.cmake.

This library becomes a dummy library

**Comment by glebius** [comment]
I see your point. Since we use options_linux.cmake with FreeBSD, then FreeBSD is kinda Linux. And cmake also thinks this way.
Doesn't convince me, I would rather treat it is a fourth option added to the list of LINUX, WIN32, APPLE. But I see your point. May I ask you to make the change that you suggest?

**Comment by ilya-fedin** [comment]
Here you go #125

**Pull request closed without merging**
