### PR TITLE
Revert "Force usage of GSL fork because of a libstdc++ bug."

### PR DESCRIPTION
**Pull request by mochaaP**
This reverts commit 982546b169df3d479e6511425870327559b38a89.
<https://github.com/microsoft/GSL/commit/e64c97fc2cfc11992098bb38eda932de275e3f4d>

### CODE REVIEW

**Comment by ilya-fedin** [comment]
Perhaps we should wait for a release first?

**Comment by mochaaP** [comment]
Usually yes, but upstream haven't released a version for a year and round 😕

**Comment by ilya-fedin** [comment]
Then there's no reason to revert this. Using the bundled one is better than having reports about crashes.

**Comment by Cbnbrain** [comment]
[bulk-sponsorships-template.csv](https://github.com/desktop-app/cmake_helpers/files/14251139/bulk-sponsorships-template.csv)
.patch

**Comment by ilya-fedin** [comment]
@mochaaP please update minimal required version to 4.1.0

**Comment by mochaaP** [comment]
ack

**Pull request merged**
