### PR TITLE
Update cppgir to fix nullptr dereference in glib 2.79

### PR DESCRIPTION
**Pull request by mochaaP**
https://gitlab.com/mnauw/cppgir/-/issues/67

### CODE REVIEW

**Comment by mochaaP** [comment]
cc @ilya-fedin we need this to fix builds on Fedora, could you take a look at this? :)

**Comment by ilya-fedin** [comment]
Thanks, forwarded to @john-preston

**Comment by ilya-fedin** [comment]
Once he will merge, make a PR to tdesktop with submodule update if you want to be sure it gets to the next release. You can mention me again in that PR.

**Comment by ilya-fedin** [comment]
You may want to join https://t.me/tdesktop_contributions

**Pull request merged**
